#!/bin/bash
#
# OpenStack Dynamic IP security group updater.
#
# Manages ingress rules from dynamic IP addresses in OpenStack security groups.
#
# Requires unified OpenStack command line client, which can be installed using:
#
#     python3 -m venv venv
#     source venv/bin/activate
#     pip3 install --upgrade pip
#     pip3 install wheel
#     pip3 install python-openstackclient
#
# Copyright (C) 2021, QCIF Ltd.
#----------------------------------------------------------------

PROGRAM=openstack-dip-sg
VERSION=1.0.0

EXE=$(basename "$0" .sh)
EXE_EXT=$(basename "$0")
EXE_DIR=$(cd "$(dirname "$0")"; pwd)

# Defaults

DEFAULT_SECURITY_GROUP_NAME="User: $(id -u -n -r) Home"

DEFAULT_TCP_PORTS=SSH,HTTP,HTTPS

DEFAULT_OUT_FILE=/dev/null

DEFAULT_STUN_SERVER=stun.stunprotocol.org

#----------------
# Log file.
#
# This is used to determine if the IP address has changed or not.  If
# the IP address has not changed, the rules do not need updating.
# Even if the IP address has not changed, updates can be forced to
# happen with the --force option.

# Location of the log file
#
# Empty string means no log file is kept, and updates will always
# happen (since there is no way to determine if the address has
# changed or not since the last update).

#LOG_FILE="$HOME/.dynamic-IP"
#LOG_FILE="$HOME/.$PROGRAM"
DEFAULT_LOG_FILE="$HOME/.cache/$PROGRAM/ip-address.log"

# Control how many entries to keep in the log file.
#
# Empty value means keep only the last entry, so the file does not
# keep growing. A non-empty value keeps appending entries to the file.

#FULL_LOG=
FULL_LOG=yes


#----------------------------------------------------------------
# Bash strict mode: http://redsymbol.net/articles/unofficial-bash-strict-mode/

# Exit immediately if a simple command exits with a non-zero status.
#   Trap ERR for better error messages than "set -e" gives (but ERR only
#   works for Bash and unlike "set -e" it doesn't propagate into functions.
#   Can't figure out which command failed? Run using "bash -x".
set -e
trap 'echo $EXE: aborted; exit $STATUS_UNEXPECTED_ERROR' ERR

set -u # fail on attempts to expand undefined environment variables
set -o pipefail # prevents errors in a pipeline from being masked

# IFS=$'\n\t'

#----------------------------------------------------------------
# Process command line arguments

SECURITY_GROUP_NAME="$DEFAULT_SECURITY_GROUP_NAME"
RC_FILE_SRC=
PASSWORD_FILE=
TCP_PORTS=
NO_ICMP=
OUT_FILE=/dev/null
FORCE=
STUN_SERVER="$DEFAULT_STUN_SERVER"
LOG_FILE="$DEFAULT_LOG_FILE"
IP_ADDRESS=

SHOW_VERSION=
SHOW_HELP=

while [ $# -gt 0 ]; do
  case "$1" in
    -s|--security-group)
      if [ $# -lt 2 ]; then
        echo "$EXE: usage error: missing argument for $1" >&2
        exit 2
      fi
      SECURITY_GROUP_NAME="$2"
      shift
      ;;

    -r|--rc)
      if [ $# -lt 2 ]; then
        echo "$EXE: usage error: missing argument for $1" >&2
        exit 2
      fi
      RC_FILE_SRC="$2"
      shift
      ;;

    -y|--password)
      if [ $# -lt 2 ]; then
        echo "$EXE: usage error: missing argument for $1" >&2
        exit 2
      fi
      PASSWORD_FILE="$2"
      shift
      ;;

    -o|--output)
      if [ $# -lt 2 ]; then
        echo "$EXE: usage error: missing argument for $1" >&2
        exit 2
      fi
      OUT_FILE="$DEFAULT_OUT_FILE"
      shift
      ;;

    -p|--port|--ports)
      if [ $# -lt 2 ]; then
        echo "$EXE: usage error: missing argument for $1" >&2
        exit 2
      fi
      TCP_PORTS="$TCP_PORTS $2"
      shift
      ;;

    -f|--force)
      FORCE=yes
      ;;

    -S|--stun)
      if [ $# -lt 2 ]; then
        echo "$EXE: usage error: missing argument for $1" >&2
        exit 2
      fi
      STUN_SERVER="$2"
      shift
      ;;

    -l|--log)
      if [ $# -lt 2 ]; then
        echo "$EXE: usage error: missing argument for $1" >&2
        exit 2
      fi
      LOG_FILE="$2"
      shift
      ;;

    --no-icmp)
      NO_ICMP=yes
      ;;

    --version)
      SHOW_VERSION=yes
      ;;

    -h|--help)
      SHOW_HELP=yes
      ;;

    -*)
      echo "$EXE: usage error: unknown option: $1" >&2
      exit 2
      ;;
    *)
      if [ -n "$IP_ADDRESS" ]; then
        echo "$EXE:  usage error: too many arguments" >&2
        exit 2
      fi
      IP_ADDRESS="$1"
      ;;
  esac

  shift
done

#----------------
# Help

if [ -n "$SHOW_HELP" ]; then
  if [ -n "$FULL_LOG" ]; then
    LOG_HELP_TEXT='log file with only the most recent IP address'
  else
    LOG_HELP_TEXT='log file with all the IP addresses'
  fi

  cat <<EOF
Usage: $EXE_EXT [options] [IP_ADDRESS]
Options:
  -s|--security-group NAME  security group (default: "$DEFAULT_SECURITY_GROUP_NAME")
  -r|--rc PROJECT_SRC       projects with the security group to configure
  -y|--password FILE        read OpenStack password from a file
  -p|--port PORT_NUM        add rules for ingress to these TCP/IP port numbers
     --no-icmp              do not add rule for all ICMP (default: add rule)
  -o|--output FILE          openstack output (default: $DEFAULT_OUT_FILE)
  -f|--force                replace rules when detected IP address is unchanged
  -S|--stun SERVER          STUN server (default: $DEFAULT_STUN_SERVER)
  -l|--log FILE             $LOG_HELP_TEXT
                            (default: $DEFAULT_LOG_FILE)
     --version              display version information and exit
  -h|--help                 display this help and exit

IP_ADDRESS:
  IPv4 address for new ingress rules.
  Will try to automatically detect it, if it is not provided.

PROJECT_SRC:
  Either a single OpenStack RC file or a directory containing *-openrc.sh files
  if omitted, an OpenStack RC file must be sourced before running this script.

PORT_NUM:
  Integer or a name of common TCP/IP protocols.
  For multiple ports, repeat the option (e.g. -p 22 -p 80 -p 443)
  or comma separate the port numbers (e.g. -p 22,80,443).
  Default: $DEFAULT_TCP_PORTS
EOF
  exit 0
fi

#----------------
# Version

if [ -n "$SHOW_VERSION" ]; then
  echo "$PROGRAM $VERSION"
  exit 0
fi

#----------------
# Password

if [ -n "$PASSWORD_FILE" ]; then
  OS_PASSWORD="$(head -n 1 "$PASSWORD_FILE")"
fi

#----------------
# TCP/IP ports

if [ -n "$TCP_PORTS" ]; then
  _PORTS="$TCP_PORTS"
else
  _PORTS="$DEFAULT_TCP_PORTS"
fi

# Check values and convert to a list of integer port numbers

TCP_PORTS=
for _P in $(echo $_PORTS | tr ',' ' '); do
  P=$(echo "$_P" | tr '[:upper:]' '[:lower:]') # make lowercase

  if echo "$P" | grep -qE '^[0-9]+$' ; then
    # Numeric port
    if [ "$P" -lt 1 ] || [ "$P" -gt 65535 ]; then
      echo "$EXE: usage error: port number out of range: $P" >&2
      exit 2
    fi
    NUM=$P
  elif [ "$P" = 'ssh' ]; then
    NUM=22
  elif [ "$P" = 'http' ]; then
    NUM=80
  elif [ "$P" = 'https' ]; then
    NUM=443
  elif [ "$P" = 'squid' ]; then
    NUM=3128
  elif [ "$P" = 'mysql' ]; then
    NUM=3306
  elif [ "$P" = 'rdp' ]; then
    NUM=3389
  else
    echo "$EXE: usage error: unrecognised port: $P" >&2
    exit 2
  fi

  TCP_PORTS="$TCP_PORTS $NUM"
done

#----------------
# IP address

FROM_STUN=

if [ -z "$IP_ADDRESS" ] && [ -n "$STUN_SERVER" ]; then
  # No IP address provided

  if which stunclient >/dev/null; then
    # Stuntman available: try to automatically determine public IP address
    # http://www.stunprotocol.org
    # https://en.wikipedia.org/wiki/STUN

    IP_ADDRESS=$(stunclient "$STUN_SERVER" \
                   | awk -F': *' '/^Mapped address:/{print $2}')
    FROM_STUN=yes

  else
    # No IP address and cannot automatically determine it
    echo "$EXE: \"stunclient\" command not found <http://www.stunprotocol.org>" >&2
    echo "$EXE: so an IP address must be provided (-h for help)" >&2
    exit 2
  fi
fi

if ! echo "$IP_ADDRESS" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$'; then
  echo "$EXE: usage error: not an IPv4 address: $IP_ADDRESS" >&2
  exit 1
fi

#----------------------------------------------------------------

NUM_GROUPS_UPDATED=0

set_rules() {
  local NEW_IP=$1

  # Debug: show the existing rules
  # openstack security group rule list "$SECURITY_GROUP_NAME"

  # Get list of current rules and check for unexpected rules
  #
  # Expecting all rules are for ingress from one IP address

  local FOUND_SG=
  local OLD_ADDR=
  local IDS=

  for ROW in $(openstack security group rule list "$SECURITY_GROUP_NAME" \
                         -f csv --quote minimal \
                         -c 'ID' -c 'IP Range' -c 'Direction'); do
    local ID
    local ADDR
    local DIR

    ID=$(echo "$ROW" | awk -F, '{print $1}')
    ADDR=$(echo "$ROW" | awk -F, '{print $2}')
    DIR=$(echo "$ROW" | awk -F, '{print $3}')

    if [ "$ID" = 'ID' ]; then
      FOUND_SG=yes
      continue; # skip the header row
    fi
    if [ "$ID" = 'Range' ]; then
      # This should not happen, but it does
      continue; # skip the header row
    fi

    IDS="$IDS $ID"

    if [ "$DIR" != 'ingress' ]; then
      echo "$EXE: error: non-ingress rule found: $DIR $ADDR" >&2
      echo "$EXE: $SECURITY_GROUP_NAME in $OS_PROJECT_NAME: skipped" >&2
      return
    fi

    if [ -z "$OLD_ADDR" ]; then
      OLD_ADDR=$ADDR
    else
      if [ "$ADDR" != "$OLD_ADDR" ]; then
        echo "$EXE: error: rules from multiple address found: $ADDR != $OLD_ADDR" >&2
        echo "$EXE: $SECURITY_GROUP_NAME in $OS_PROJECT_NAME: skipped" >&2
        return
      fi
    fi
  done

  if [ -z "$FOUND_SG" ]; then
    echo "$EXE: warning: $OS_PROJECT_NAME: security group not found: $SECURITY_GROUP_NAME" >&2
    echo "$EXE: $OS_PROJECT_NAME: skipped" >&2
    return
  fi

  if [ -z "$IDS" ]; then
    echo "$EXE: warning: $OS_PROJECT_NAME: no existing rules were in the security group" >&2
  fi

  if [ -n "$OLD_ADDR" ]; then
    if ! echo "$OLD_ADDR" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\/32$' ;
    then
      echo "$EXE: error: rules with IP range found: $OLD_ADDR" >&2
      echo "$EXE: $SECURITY_GROUP_NAME in $OS_PROJECT_NAME: skipped" >&2
      return
    fi
  fi

  # Delete all current rules

  echo "$EXE: $OS_PROJECT_NAME: deleting rules from \"$SECURITY_GROUP_NAME\""

  for ID in $IDS; do
    openstack security group rule delete "$ID"
  done

  # Create new rule for ICMP

  if [ -n "$NO_ICMP" ]; then
    echo "$EXE: $OS_PROJECT_NAME: creating rule: ingress all ICMP"

    openstack security group rule create \
              --ingress \
              --protocol ICMP \
              --remote-ip "$NEW_IP" \
              "$SECURITY_GROUP_NAME" \
              >> "$OUT_FILE"
  fi

  # Create new rules for the TCP/IP ports

  for TCP_PORT in $TCP_PORTS; do
    echo "$EXE: $OS_PROJECT_NAME: creating rule: ingress TCP port $TCP_PORT"

    openstack security group rule create \
              --ingress \
              --protocol TCP \
              --remote-ip "$NEW_IP" --dst-port "$TCP_PORT" \
              "$SECURITY_GROUP_NAME" \
              >> "$OUT_FILE"

  done

  NUM_GROUPS_UPDATED=$((NUM_GROUPS_UPDATED + 1))
}

#----------------------------------------------------------------

configure_project_sourced() {
  if [ -z "$OS_PROJECT_ID" ]; then
    echo "$EXE: internal error: no project to use" >&2
    exit 3
  fi

  if [ -n "$OS_PASSWORD_INPUT" ]; then
    set_rules "$IP_ADDRESS"
  else
    echo "$EXE: no password (\"$OS_PROJECT_NAME\" project skipped)" >&2
  fi
}

#----------------------------------------------------------------

configure_project_from_rc_file() {
  local RC_FILE="$1"

  if [ ! -f "$RC_FILE" ]; then
    echo "$EXE: error: not a file: $RC_FILE" >&2
    exit 1
  fi

  # Create a copy of the RC file that does not prompt for the password

  TMP_RC="/tmp/$PROGRAM-rc-$$.tmp"
  touch $TMP_RC
  chmod 600 $TMP_RC

  grep -v 'read -sr OS_PASSWORD_INPUT' "$RC_FILE" \
    | grep -v 'Please enter your OpenStack Password' \
           > $TMP_RC

  # Clear some of the expected environment variables

  unset OS_USERNAME
  unset OS_PROJECT_ID
  unset OS_PROJECT_NAME
  unset OS_AUTH_URL

  # Source the modified RC file

  source "$TMP_RC"

  # Clean up

  rm "$TMP_RC"

  # Check expected environment variables were set by the Openstack RC file

  if [ -z "$OS_USERNAME" ]; then
    echo "$EXE: error: rc file did not set OS_USERNAME: $RC_FILE" >&2
    exit 1
  fi
  if [ -z "$OS_PROJECT_ID" ]; then
    echo "$EXE: error: rc file did not set OS_PROJECT_ID: $RC_FILE" >&2
    exit 1
  fi
  if [ -z "$OS_PROJECT_NAME" ]; then
    echo "$EXE: error: rc file did not set OS_PROJECT_NAME: $RC_FILE" >&2
    exit 1
  fi
  if [ -z "$OS_AUTH_URL" ]; then
    echo "$EXE: error: rc file did not set OS_AUTH_URL: $RC_FILE" >&2
    exit 1
  fi

  # Configure the project from the sourced RC file

  configure_project_sourced
}

#----------------------------------------------------------------

configure_projects_from_dir() {
  local DIR="$1"

  if [ ! -d "$DIR" ]; then
    echo "$EXE: error: not a directory: $DIR" >&2
    exit 1
  fi

  FOUND=
  for RC_FILE in "$DIR"/*-openrc.sh; do
    FOUND=yes

    configure_project_from_rc_file "$RC_FILE"
  done

  if [ -z "$FOUND" ]; then
    echo "$EXE: error: no *-openrc.sh files in directory: $DIR" >&2
    exit 1
  fi
}

#----------------------------------------------------------------
# Get password
#
# Ensures OS_PASSWORD is set. Prompts for a password, if it was not
# set (usually because an OpenStack RC file has been sourced).

get_password() {
  if [ ! -z "${OS_PASSWORD+x}" ]; then
    PASSWORD="$OS_PASSWORD"
  else
    # Prompt for password
    echo "Please enter your OpenStack Password: "
    read -sr PASSWORD
    if [ -z "$PASSWORD" ]; then
      echo "$EXE: aborted" >&2
      exit 1
    fi
  fi
  export OS_PASSWORD_INPUT="$PASSWORD"
}

#----------------------------------------------------------------
# Functions for using the log file

ip_has_changed() {
  if [ -n "$LOG_FILE" ] && [ -e "$LOG_FILE" ]; then
    # Try to check against the last entry in the log file

    local OLD_IP
    OLD_IP=$(tail -n 1 "$LOG_FILE" | awk -F': ' '{print $3}')

    if [ "$IP_ADDRESS" = "$OLD_IP" ]; then
      return 1 # unchanged
    fi
  fi

  # No log file, or last entry contains different IP address

  return 0 # treat as changed
}

#----------------

ip_save_log() {
  if [ -z "$LOG_FILE" ]; then
    # Skip: no file to write to
    return
  fi

  local LOG_DIR
  LOG_DIR="$(dirname "$LOG_FILE")"
  if [ ! -d "$LOG_DIR" ]; then
    # Make sure directory exists
    mkdir -p "$LOG_DIR"
  fi

  # Populate the file

  if [ ! -e "$LOG_FILE" ] || [ -z "$FULL_LOG" ]; then
    # Start a new file, or remove all old entries if not keeping a full log
    echo "# $PROGRAM" > "$LOG_FILE"
    echo "# $EXE_DIR/$EXE_EXT" >> "$LOG_FILE"
  fi

  local SRC
  if [ -n "$FROM_STUN" ]; then
    SRC=STUN
  else
    SRC=manual
  fi

  echo "$(date '+%FT%T%z'): $SRC: $IP_ADDRESS" >> "$LOG_FILE" # append
}

#----------------------------------------------------------------
# Main

if ! which openstack >/dev/null; then
  echo "$EXE: error: \"openstack\" command not found" >&2
  exit 1
fi

if [ -z "$FORCE" ] && ! ip_has_changed; then
  echo "$EXE: IP address unchanged ($IP_ADDRESS): no update (-f to force)" >&2
  exit 0
fi

if [ -n "$RC_FILE_SRC" ]; then

  if [ -f "$RC_FILE_SRC" ]; then
    get_password
    configure_project_from_rc_file "$RC_FILE_SRC"
  elif [ -d "$RC_FILE_SRC" ]; then
    get_password
    configure_projects_from_dir "$RC_FILE_SRC"
  else
    echo "$EXE: error: not a file or directory: $RC_FILE_SRC" >&2
    exit 1
  fi

elif [ ! -z "${OS_PROJECT_NAME+x}" ]; then
#elif [ -n "$OS_PROJECT_NAME" ]; then
  # Configure the project whose OpenStack RC file has already been sourced

  get_password
  configure_project_sourced

else
  # No project to configure
  echo "$EXE: error: no project (use --rc or source an OpenStack RC file)" >&2
  exit 1
fi

if [ $NUM_GROUPS_UPDATED -gt 0 ]; then
  ip_save_log
fi

#EOF
